In [2]:
import numpy as np
arr1=np.array([[1,2,3],[2,4,5],[4,7,8]])
arr1
zeros_arr=np.zeros(5,dtype="int")
zeros_arr
zeros_arr.dtype

dtype('int64')

In [3]:
a=np.array([[1,2,3,4],[4,5,6,7],[6,8,4,9],])
a.dtype

dtype('int64')

In [4]:
c=np.array([[1,2,3],[5,7,9]])
b=np.swapaxes(c,0,1)
b
c.max()
a.reshape(2,6)

array([[1, 2, 3, 4, 4, 5],
       [6, 7, 6, 8, 4, 9]])

In [5]:
arr = np.linspace(1, 6, 12)
arr
arr_2d = arr.reshape(3, 4)
arr_2d
import numpy as np

In [6]:
print("Original array:")
print(arr)

sorted_axis0 = np.sort(arr, axis=0)
print("\nSorted along axis=0 (by columns):")
print(sorted_axis0)



Original array:
[1.         1.45454545 1.90909091 2.36363636 2.81818182 3.27272727
 3.72727273 4.18181818 4.63636364 5.09090909 5.54545455 6.        ]

Sorted along axis=0 (by columns):
[1.         1.45454545 1.90909091 2.36363636 2.81818182 3.27272727
 3.72727273 4.18181818 4.63636364 5.09090909 5.54545455 6.        ]


In [7]:
# Creating Array
array1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)


[[1 2 3]
 [2 4 5]
 [4 7 8]]


In [8]:
# Printing datatype
print(array1.dtype)

int64


In [9]:
# Total size of array
array1.size

8

In [10]:
# Changing shape of array
array1.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
# Creating 2nd array
array2=np.array([2,3,4,9,5,8,1])

In [12]:
print(array2)

[2 3 4 9 5 8 1]


In [13]:
# Indexing of array
print(array2[-7])

2


In [14]:
# mathematical operations
x=np.array([[2,3,4,5],[7,8,9,6]])
y=np.array([[5,2,4,5],[6,9,5,2]])
print("Addition is :",x+y)
print("Subtraction is :",x-y)
print("Multiplication  is :",x*y)
print("Division is :",x/y)

Addition is : [[ 7  5  8 10]
 [13 17 14  8]]
Subtraction is : [[-3  1  0  0]
 [ 1 -1  4  4]]
Multiplication  is : [[10  6 16 25]
 [42 72 45 12]]
Division is : [[0.4        1.5        1.         1.        ]
 [1.16666667 0.88888889 1.8        3.        ]]


In [15]:
# Min and max index
k=np.array([1,2,3,4,5,6,7])
print(np.argmax(k))
print(np.argmin(k))


6
0


In [16]:
# Difference between two numbers
print(np.diff(k))

[1 1 1 1 1 1]


In [ ]:
# linespace 
array=np.linspace(1,10,5)
print(array)

[ 1.    3.25  5.5   7.75 10.  ]
