In [4]:
# Create a 1D NumPy Array
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", array1)


1D Array: [1 2 3 4 5]


In [6]:
# Create a 2D NumPy Array
array2 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\n2D Array:")
print(array2)


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Shape of array2
print("\nShape of array2:")
print(array2.shape)


Shape of array2:
(3, 3)


In [8]:
# Reshape array2 to shape (1, 9)
reshaped_array = array2.reshape(1, 9)
print("\nReshaped Array (1x9):")
print(reshaped_array)


Reshaped Array (1x9):
[[1 2 3 4 5 6 7 8 9]]


In [9]:
# Access element at row 1, column 2
element = array2[1, 2]
print("\nElement at row 1, column 2:")
print(element)


Element at row 1, column 2:
6


In [10]:
# Slice first 2 rows and first 2 columns
sliced_array = array2[:2, :2]
print("\nSliced Array (first 2 rows and first 2 columns):")
print(sliced_array)


Sliced Array (first 2 rows and first 2 columns):
[[1 2]
 [4 5]]


In [11]:
# Add 10 to every element in array2
added_array = array2 + 10
print("\nArray after adding 10:")
print(added_array)


Array after adding 10:
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [12]:
# Calculate Mean and Standard Deviation of array2
mean_val = np.mean(array2)
std_val = np.std(array2)
print("\nMean of array2:")
print(mean_val)
print("Standard Deviation of array2:")
print(std_val)


Mean of array2:
5.0
Standard Deviation of array2:
2.581988897471611


In [13]:
# Generate a random 3x3 array
random_array = np.random.rand(3, 3)
print("\nRandom 3x3 Array:")
print(random_array)


Random 3x3 Array:
[[0.53098974 0.9718064  0.55353984]
 [0.10237799 0.84317265 0.63756105]
 [0.66730281 0.70784857 0.17860351]]


In [14]:
# Matrix multiplication of array2 and its transpose
matrix_product = np.dot(array2, array2.T)
print("\nMatrix Multiplication (array2 * array2.T):")
print(matrix_product)


Matrix Multiplication (array2 * array2.T):
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
