# Om khemnar 

# Import Library

In [70]:
import numpy as np

# Creating Array

In [71]:
# 1D Array
arr1 = np.array([100, 200, 300, 400, 500])

In [72]:
# 2D Array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [73]:

# 3D Array
arr3 = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])

In [74]:
# Using arange
arr_range = np.arange(1, 11)

In [75]:
# Using linspace
arr_lin = np.linspace(0, 1, 5)

In [76]:

# Zeros, Ones, Identity
arr_zeros = np.zeros((2,3))
arr_ones = np.ones((3,3))
arr_eye = np.eye(3)

# Array Attributes

In [77]:
# shape
print("Shape:", arr2.shape)


Shape: (2, 3)


In [78]:
# Dimensions
print("Dimensions:", arr2.ndim)

Dimensions: 2


In [79]:
# Size
print("Size:", arr2.size)

Size: 6


In [80]:
#Data Type
print("Data Type:", arr2.dtype)

Data Type: int64


# Indexing & Slicing

In [81]:
print(arr1[0])          # First element

100


In [82]:
print(arr1[-1])         # Last element

500


In [83]:
print(arr1[1:4])        # Slice

[200 300 400]


In [84]:
print(arr2[0, 2])       # 1st row, 3rd column

3


In [85]:
print(arr2[:,1])        # All rows, 2nd column

[2 5]


# Mathematical Operations

In [86]:
a = np.array([5, 10, 15])
b = np.array([2, 4, 6])

In [87]:
print("Addition:", a + b)         # Addition
print("Subtraction:", a - b)      # Subtraction
print("Multiplication:", a * b)   # Element-wise Multiplication
print("Division:", a / b)         # Element-wise Division
print("Square:", np.square(a))    # Square
print("Square Root:", np.sqrt(a))  # Square Root
print("Exponent:", np.exp(b))      # Exponential
print("Logarithm:", np.log(a))     # Natural Logarithm
print("Dot Product:", np.dot(a, b))  # Dot Product

Addition: [ 7 14 21]
Subtraction: [3 6 9]
Multiplication: [10 40 90]
Division: [2.5 2.5 2.5]
Square: [ 25 100 225]
Square Root: [2.23606798 3.16227766 3.87298335]
Exponent: [  7.3890561   54.59815003 403.42879349]
Logarithm: [1.60943791 2.30258509 2.7080502 ]
Dot Product: 140


# Statistical Functions

In [88]:
data = np.array([12, 15, 20, 36, 18, 22, 30, 25])

In [89]:
print("Mean:", np.mean(data))                 # Mean
print("Median:", np.median(data))             # Median
print("Standard Deviation:", np.std(data))    # Standard Deviation
print("Variance:", np.var(data))              # Variance
print("Minimum:", np.min(data))               # Minimum
print("Maximum:", np.max(data))               # Maximum
print("Sum:", np.sum(data))                   # Sum
print("Index of Min:", np.argmin(data))       # Index of Minimum

Mean: 22.25
Median: 21.0
Standard Deviation: 7.39509972887452
Variance: 54.6875
Minimum: 12
Maximum: 36
Sum: 178
Index of Min: 0


# Reshaping & Concatenation

In [90]:
arr = np.arange(1, 13)

reshaped = arr.reshape(3,4)
flattened = reshaped.flatten()

concat = np.concatenate((arr1, b))
stacked = np.vstack((a, b))
hstacked = np.hstack((a, b))

# Sorting & Unique

In [91]:
unsorted = np.array([5, 2, 9, 1, 5, 6])
print("Sorted:", np.sort(unsorted))
print("Unique:", np.unique(unsorted))


Sorted: [1 2 5 5 6 9]
Unique: [1 2 5 6 9]


# User-Defined Dataset Example

In [92]:
# Dataset: Marks of 5 students in 3 subjects
marks = np.array([[78, 85, 90],
                  [88, 92, 76],
                  [95, 80, 85],
                  [70, 75, 60],
                  [65, 68, 72]])

print("Dataset:\n", marks)

Dataset:
 [[78 85 90]
 [88 92 76]
 [95 80 85]
 [70 75 60]
 [65 68 72]]


In [93]:
# Average marks per student
avg_student = np.mean(marks, axis=1)
print("Average marks of each student:", avg_student)


Average marks of each student: [84.33333333 85.33333333 86.66666667 68.33333333 68.33333333]


In [94]:
# Average marks per subject
avg_subject = np.mean(marks, axis=0)
print("Average marks of each subject:", avg_subject)

Average marks of each subject: [79.2 80.  76.6]


In [95]:
# Highest marks
print("Highest mark overall:", np.max(marks))

Highest mark overall: 95


In [96]:
# Lowest marks
print("Lowest mark overall:", np.min(marks))

Lowest mark overall: 60


In [97]:
# Sorting marks of each student
print("Sorted marks:\n", np.sort(marks))

Sorted marks:
 [[78 85 90]
 [76 88 92]
 [80 85 95]
 [60 70 75]
 [65 68 72]]
